FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# cpoy csproj and restore as a distinct layer
COPY *.csproj ./
RUN dotnet restore

#copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# build a runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "E-Commerce.dll"]